#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <wx/filedlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/colourdata.h>
#include <wx/colordlg.h>
#include <tuple>
#include "wec.h"


/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void wczytajOnButtonClick( wxCommandEvent& event );
		void obrot_x_sliderOnScroll( wxScrollEvent& event );
		void obrot_y_sliderOnScroll( wxScrollEvent& event );
		void obrot_z_sliderOnScroll( wxScrollEvent& event );
		void focus_sliderOnScroll( wxScrollEvent& event );
		void zapiszOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members
		Matrix4 rotuj_x(double x);
		Matrix4 rotuj_y(double y);
		Matrix4 rotuj_z(double z);




};


#endif // __GUIMyFrame1__
